### ISSUE TITLE
请问，你的LVGL是用什么工具设计的UI吗？还有那个切换有弹性的效果

### ISSUE THREAD

**Issue by zouzhe1** [Ft-Available/RX5808-Div#13]

**Comment by Ft-Available** [comment]
lvgl就是一个UI框架，界面是基于这个框架做的，弹性的效果是lvgl自带的，有许多效果，线性，弹性，窗帘式等。。。。

**Comment by zouzhe1** [comment]
@Ft-Available 我用过LVGL。所以我问的是你用的什么软件，弄LVGL。比如nxp的guider。还有lvgl自己也出了一个收费的软件。因为我觉得你画的这个很好。我自己弄的特差。

**Comment by Ft-Available** [comment]
借助了PhotoShop，把界面画出来，然后用仓库里面的Visual Studio模拟器设计，跑一下，LVGL官方的一些工具我自己没有用过，但是用这些工具应该会更便捷，只不过需要学习一下。
