### ISSUE TITLE
大佬，请问海星D1的刷了咱这个固件后五维按键不好使了，想加点东西求帮助

### ISSUE THREAD

**Issue by sharkor** [Ft-Available/RX5808-Div#14]
我想在接收机上学习一下esp32的开发，自己加点功能开发试试，现在手头用的是贝壳的海星D1，刷了咱的固件后五维按键失效，问了客服，说是您给开发的，特来求教，是否可以把贝壳D1的源代码分享一下，非常感谢

**Comment by Ft-Available** [comment]
按键ad分压的电阻值他们好像改过，具体多少并不清楚，可以打开按键分压采样的打印，然后修改一下即可
![未标题-1](https://github.com/Ft-Available/RX5808-Div/assets/66466560/bcd493c4-e72a-4678-aa37-e06c6c346d97)

**Comment by sharkor** [comment]
非常感谢，帮了大忙了

**Comment by sharkor** [comment]
> 按键修改广告分压的抵抗值他们希望改过，具体多少并穆斯林，可以打开按键分压采样的打印，然后一下就可以了 ![未标题-1](https://user-images.githubusercontent.com/66466560/268297940-bcd493c4-e72a-4678-aa37-e06c6c346d97.jpg)

不好意还得继续打扰一下，还是出了点问题，我这里打印的值是0，我怀疑他们使用的是不同的ADC引脚。

**Comment by sharkor** [comment]
> 按键ad分压的电阻值他们好像改过，具体多少并不清楚，可以打开按键分压采样的打印，然后修改一下即可 ![未标题-1](https://user-images.githubusercontent.com/66466560/268297940-bcd493c4-e72a-4678-aa37-e06c6c346d97.jpg)

不好意还得继续打扰一下，还是出了点问题，我这里打印的值是0，我怀疑他们使用的是不同的ADC引脚。

**Comment by Ft-Available** [comment]
hwver.h里面切一下模组版的，如果不行那就是他们改过了

**Comment by sharkor** [comment]
> hwver.h里面切一下模组版的，如果不行那就是他们改过了

好的谢谢啦，我试试实在不行就重新弄个主控板了

**Comment by sharkor** [comment]
> hwver.h里面切一下模组版的，如果不行那就是他们改过了

再次感谢，切换了模组后直接可以了，阻值也是不用改的
