### ISSUE TITLE
Chip CPU frequency rated for 160MHz, configured for 240MHz. Modify CPU frequency in menucog

### ISSUE THREAD

**Issue by lyh-96** [Ft-Available/RX5808-Div#15]
小板凳您好,
我想飞线加上OSD功能, 按照林面包的方法短接上侧排针倒数第二第三个, 并引至彩色LED灯右下引脚
尝试烧录你的固件后, 出现如标题所示错误一直重启, 我也使用的是esp32 pico D4理论是是240Hz芯片才对
我尝试clone你的仓库, 自行编译, 出现编译错误:RX5808-Div/Firmware/ESP32/RX5808/main/gui/lvgl_driver/lv_port_disp.c:15:10: fatal error: capi_video.h: No such file or directory
我是使用的是最新的esp_idf v5.2版本

我想请教如下问题:
1.capi_video.h是esp_idf的库还是第三方库, 要如何获取这个库, 解决这个编译错误
2.你通常使用哪个esp_idf版本编译
3.我的飞线方法是否正确
4.您是否了解esp32 pico D4有160MHz的主频型号, 如果我的是160MHz主频是否sdkconfig修改CPU频率即可

期待您的回复, 感激不尽!

附开机错误日志如下:
rst:0x3 (SW_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 188777542, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:7320
load:0x40078000,len:14976
load:0x40080400,len:3688
entry 0x4008067c
E (58) boot.esp32: Chip CPU frequency rated for 160MHz, configured for 240MHz. Modify CPU frequency in menucog
ets Jun  8 2016 00:22�ets Jun  8 2016 00:22:57

**Comment by Ft-Available** [comment]
1.git clone 后 git submodule update --init --recursive ，或者进入chisbread仓库下载替换即可
2.esp-idf4.0
3.正确，建议看我立创开源的飞线方法
4 espidf支持配置esp32主频80M 160M 240M，并没有还根据频率分型号的，编译通过下载应该就可以了。
5.可以立创或者b站找我。
