### ISSUE TITLE
Shell model for fatshark HDO

### ISSUE THREAD

**Issue by luttesudo** [Ft-Available/RX5808-Div#2]
Do you have a case model for the fatshark HDO? Or is there a modifiable file for O4X?

**Comment by Ft-Available** [comment]
I don't have fat shark glasses, so I didn't design the 3D model, now I have uploaded the 04X modifiable model, which was designed with SolidWords.

**Comment by luttesudo** [comment]
Thank you for the upload, I will share the model after I revise it, it may be later, I am more busy
