### ISSUE TITLE
看到esp32修改了几个电容，请问这个改动的是否重要

### ISSUE THREAD

**Issue by Mason-star** [Ft-Available/RX5808-Div#3]

**Comment by Ft-Available** [comment]
不知道你说的是哪几个电容，和esp相连的C11 10nf不可更改更不可缺少，其次esp32 天线Π型电路的电容和电感不可更改，其余电容大都为滤波作用，可以适当更改和替换。

**Comment by Mason-star** [comment]
<img width="436" alt="截屏2022-07-23 19 09 33" src="https://user-images.githubusercontent.com/54500461/180602574-71e4a37c-21b3-4211-b838-53e08c6e5294.png">
<img width="421" alt="截屏2022-07-23 19 10 07" src="https://user-images.githubusercontent.com/54500461/180602596-50cdb29d-e0e7-483b-aac8-c6d09bbfcc0d.png">

之前一个版本，bom表除了c11以外都为100nf，这两天，仔细看了一下原理图，发现c15和c16是1.2pf和1.5pf，c10为100nf和bom表有些出入，是pcb改动导致的bom表变动，还是bom表有误？

**Comment by Ft-Available** [comment]
BOM表有误，已修改并上传，主要参考原理图
