### ISSUE TITLE
OSD支持 - OSD Support Request

### ISSUE THREAD

**Issue by ChisBread** [Ft-Available/RX5808-Div#6]
hello, 这里是刚接触嵌入式几天的新手(计算机专业,目前是后端开发)，说的不对还请多多包涵

**功能描述:**
参考RF接收机提供的使用接收屏调参的OSD功能，在调整频段时无需摘下眼镜
**ESP32 A/V输出:**
我研究了一下esp32通过DAC实现A/V输出的可行性，似乎效果相当不错
《ESP32 Composite Video(ESP32 合成视频)》
https://www.youtube.com/watch?v=5t1_XNc3vNw 
https://www.bilibili.com/video/BV12V411o7xW 
**改造项目的可能性:**
TOP:
我阅读了固件代码和原理图，DAC引脚目前被IPS_BLK和LED_STRIP占用了，可能需要另想办法。不清楚74HC4066是否能加一路video输入，按我的理解应该是不够用了（4路的输入被a0,a1,v0,v1占了, 如果用6路的开关也许可以实现这个功能?)
BUT: 
好像不需要做什么改动

最后感谢作者的开源，让我有一个非常有趣的入门体验！没有什么比学习新东西更快乐的了 :D

**Comment by ChisBread** [comment]
Supports [LVGL](https://lvgl.io/) graphics library
https://github.com/aquaticus/esp32_composite_video_lib

**Comment by ChisBread** [comment]
https://github.com/ChisBread/RX5808-Div/tree/composite_video
我自己写了
![IMG_20220828_205946](https://user-images.githubusercontent.com/11482833/187103909-2f10c204-9fb7-46ea-98c2-fa9a08dfa7d9.jpg)

**Comment by Ft-Available** [comment]
这个很有意思，你已经实现了，(●'◡'●)。

**Comment by ChisBread** [comment]
是啊，不知道你在不在蛋总（独自飞舞）的群里
我写好固件，修改了原理图（去掉了RGB，加上了双刀单掷模拟开关），蛋总帮我修改了PCB然后去打样了
长按解锁后，VIDEO切换到DAC_VIDEO，这样眼镜里就能看到OSD UI
因为和主线代码相差比较多，硬件也不一样，所以单开了分支，希望之后这个功能可以合并到主线

**Comment by caixiaohai0** [comment]
> 是啊，不知道你在不在蛋总（独自飞舞）的群里 我写好固件，修改了原理图（去掉了RGB，加上了双刀单掷模拟开关），蛋总帮我修改了PCB然后去打样了 长按解锁后，VIDEO切换到DAC_VIDEO，这样眼镜里就能看到OSD UI 因为和主线代码相差比较多，硬件也不一样，所以单开了分支，希望之后这个功能可以合并到主线

大佬，可以上传原理图到你的分支里？

**Comment by ChisBread** [comment]
> > 是啊，不知道你在不在蛋总（独自飞舞）的群里 我写好固件，修改了原理图（去掉了RGB，加上了双刀单掷模拟开关），蛋总帮我修改了PCB然后去打样了 长按解锁后，VIDEO切换到DAC_VIDEO，这样眼镜里就能看到OSD UI 因为和主线代码相差比较多，硬件也不一样，所以单开了分支，希望之后这个功能可以合并到主线
> 
> 大佬，可以上传原理图到你的分支里？


我用macOS不能直接修改作者的工程文件（需要转成其它格式），所以没办法可协作地改动repo里的原理图
出于可维护性考虑，这部分的希望还是作者来统一修改
这是我的原理图，圈起来的是修改的部分(待勘误)，如果作者同步完，验证无误的话。可以在我的[composite_video](https://github.com/ChisBread/RX5808-Div/tree/composite_video)分支合并后提交到主线。
![DB5E4BC4C2B2533C1475AA968AA86441](https://user-images.githubusercontent.com/11482833/187167280-9612c3a4-2e24-46df-ae4f-24c9fe9edbcc.jpg)

这个DAC VIDEO也许不仅可以作为OSD，别的玩法可以在合并后研究研究

**Comment by ChisBread** [comment]
video功能合并前，先打开这个issue吧

**Comment by ChisBread** [comment]
这个原理图图中有一处不规范，type-c的CC1 CC2应该分别接下拉电阻

**Comment by caixiaohai0** [comment]
大佬，你原理图部分是按照那个模块或芯片画的，我对比了一下esp32 wroom-32d这个模块的原理图发现闪存这部分IO和你的不一样 
![Dingtalk_20220830105303](https://user-images.githubusercontent.com/46605553/187338521-dc36e23e-2100-44da-8e4e-c2b2c654ed94.jpg)
![Dingtalk_20220830105657](https://user-images.githubusercontent.com/46605553/187338636-a9d6e01d-79f9-44b1-a68d-633da5fc17c7.jpg)

**Comment by caixiaohai0** [comment]
> > > 是啊，不知道你在不在蛋总（独自飞舞）的群里 我写好固件，修改了原理图（去掉了RGB，加上了双刀单掷模拟开关），蛋总帮我修改了PCB然后去打样了 长按解锁后，VIDEO切换到DAC_VIDEO，这样眼镜里就能看到OSD UI 因为和主线代码相差比较多，硬件也不一样，所以单开了分支，希望之后这个功能可以合并到主线
> > 
> > 
> > 大佬，可以上传原理图到你的分支里？
> 
> 我用macOS不能直接修改作者的工程文件（需要转成其它格式），所以没办法可协作地改动repo里的原理图 出于可维护性考虑，这部分的希望还是作者来统一修改 这是我的原理图，圈起来的是修改的部分(待勘误)，如果作者同步完，验证无误的话。可以在我的[composite_video](https://github.com/ChisBread/RX5808-Div/tree/composite_video)分支合并后提交到主线。 ![DB5E4BC4C2B2533C1475AA968AA86441](https://user-images.githubusercontent.com/11482833/187167280-9612c3a4-2e24-46df-ae4f-24c9fe9edbcc.jpg)
> 
> 这个DAC VIDEO也许不仅可以作为OSD，别的玩法可以在合并后研究研究

大佬，你原理图部分是按照那个模块或芯片画的，我对比了一下esp32 wroom-32d这个模块的原理图发现闪存这部分IO和你的不一样
![Dingtalk_20220830105657](https://user-images.githubusercontent.com/46605553/187338772-c4115f76-c2ab-4ce2-80fa-479ee5dd5ba4.jpg)
![Dingtalk_20220830105303](https://user-images.githubusercontent.com/46605553/187338796-1bcb6134-8502-418c-9d58-3b3e4cbc5938.jpg)

**Comment by ChisBread** [comment]
> > > > 是啊，不知道你在不在蛋总（独自飞舞）的群里 我写好固件，修改了原理图（去掉了RGB，加上了双刀单掷模拟开关），蛋总帮我修改了PCB然后去打样了 长按解锁后，VIDEO切换到DAC_VIDEO，这样眼镜里就能看到OSD UI 因为和主线代码相差比较多，硬件也不一样，所以单开了分支，希望之后这个功能可以合并到主线
> > > 
> > > 
> > > 大佬，可以上传原理图到你的分支里？
> > 
> > 
> > 我用macOS不能直接修改作者的工程文件（需要转成其它格式），所以没办法可协作地改动repo里的原理图 出于可维护性考虑，这部分的希望还是作者来统一修改 这是我的原理图，圈起来的是修改的部分(待勘误)，如果作者同步完，验证无误的话。可以在我的[composite_video](https://github.com/ChisBread/RX5808-Div/tree/composite_video)分支合并后提交到主线。 ![DB5E4BC4C2B2533C1475AA968AA86441](https://user-images.githubusercontent.com/11482833/187167280-9612c3a4-2e24-46df-ae4f-24c9fe9edbcc.jpg)
> > 这个DAC VIDEO也许不仅可以作为OSD，别的玩法可以在合并后研究研究
> 
> 大佬，你原理图部分是按照那个模块或芯片画的，我对比了一下esp32 wroom-32d这个模块的原理图发现闪存这部分IO和你的不一样 ![Dingtalk_20220830105657](https://user-images.githubusercontent.com/46605553/187338772-c4115f76-c2ab-4ce2-80fa-479ee5dd5ba4.jpg) ![Dingtalk_20220830105303](https://user-images.githubusercontent.com/46605553/187338796-1bcb6134-8502-418c-9d58-3b3e4cbc5938.jpg)

原项目是ESP32 Pico D4 (不是大佬，真的才学两周)

**Comment by caixiaohai0** [comment]
> ESP32 Pico D4

可以考虑分支个esp32 wroom-32d模块固件吗？找了一圈没找到哪个是io定义的，还是技术不到家，23333

**Comment by ChisBread** [comment]
> > ESP32 Pico D4
> 
> 可以考虑分支个esp32 wroom-32d模块固件吗？找了一圈没找到哪个是io定义的，还是技术不到家，23333

和主题无关的内容请另提issue

**Comment by ChisBread** [comment]
@Ft-Available https://github.com/ChisBread/DawnOfAV 
似乎彩色视频也是可以合成的，我在尝试移植

**Comment by ChisBread** [comment]
hello 我已经实现了稳定的彩色输出，并提交了PR
演示视频:
https://www.bilibili.com/video/BV1kD4y1B7WB

**Comment by ChisBread** [comment]
已解决，见:
https://github.com/Ft-Available/RX5808-Div/pull/12
